### ISSUE TITLE
帮忙看下这是什么错误，谢谢。

### ISSUE THREAD

**Issue by huangjianke** [fangjh13/Ftown#1]
![image](https://user-images.githubusercontent.com/8692455/27043060-7b2ee7a6-4fcb-11e7-9b28-cb9c162e877a.png)

**Comment by fangjh13** [comment]
`cd到`app`目录下运行`python3 manage.py runserver`

**Comment by huangjianke** [comment]
一样的错误。

**Comment by fangjh13** [comment]
那把`from . import mail`换成`from app import mail`改成绝对导入看看

**Comment by huangjianke** [comment]
@fangjh13 能说下你的开发环境是怎样的么

**Comment by fangjh13** [comment]
開發用Mint+pycharm 正式上是centos7
